# Generated by Django 3.1.6 on 2021-02-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210218_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='bodypart',
            field=models.TextField(null=True),
        ),
    ]
