# Generated by Django 3.1.6 on 2021-03-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210218_2147'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workout_content',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_content',
            field=models.ManyToManyField(to='main.Exercise'),
        ),
    ]
