# Generated by Django 3.1.6 on 2021-03-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210304_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_content',
            new_name='workout_exercises',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_description',
            field=models.TextField(default='a', max_length=250, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
