# Generated by Django 3.1.6 on 2021-02-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210228_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='user',
            new_name='account',
        ),
    ]
