# Generated by Django 3.1.4 on 2021-03-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20210304_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='workout_title',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_difficulty',
            field=models.IntegerField(default=2),
        ),
    ]
