# Generated by Django 3.1.4 on 2021-03-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20210310_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workout_description',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_bodyparts',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
