# Generated by Django 3.1.4 on 2021-03-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20210310_2140'),
        ('workouts', '0005_auto_20210310_2140'),
    ]

    operations = [
    ]
