# Generated by Django 3.1.4 on 2021-03-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_merge_20210310_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_bodyparts',
            new_name='bodyparts',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='workout_difficulty',
            new_name='difficulty',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='workout_exercises',
            new_name='exercises',
        ),
    ]
