# Generated by Django 3.1.4 on 2021-04-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_auto_20210310_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.TextField(default='prebuilt'),
            preserve_default=False,
        ),
    ]
